directories:
  pipline_path: "pip_line"
  raw_data: "Data/Raw-Data"
  prep_data: "Data/Prep-Data"
  modules: "Modules"
  serving_model: "Model_Serving"
  tun_best_param: "Tuner/best_hyperparameters/best_hyperparameters.txt"
pipline:
  name: 'rec_sys_imdb'

train_args:
  epochs: 50
  label_key: 'My Rate'
  features_key:
    - "IMDb_Rating"
    - "Description"
  STRING_FEATURE:
    - "Description"
  FLOAT_FEATURE:
    - "IMDb_Rating"
    - "My Rate"
  early_stp_patience: 10


